# Generated by Django 5.0.6 on 2024-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_visiters_additionalsourcesmodels_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalsourcesmodels',
            name='visitors',
            field=models.IntegerField(default=1),
        ),
    ]
