# Generated by Django 5.0.6 on 2024-05-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth_app.usertype'),
        ),
    ]
