# Generated by Django 5.0.6 on 2024-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_myuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='codeSklad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
