# Generated by Django 5.0.6 on 2024-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_myuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='profile/profile_pc/nouserimage.png', upload_to='profile/profile_pics'),
        ),
    ]
