# Generated by Django 5.0.6 on 2024-05-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='profile/profile_pics/nouserimage.png', upload_to='profile/profile_pics'),
        ),
    ]
